// game.js - Core game logic for AquaFlow
// Handles levels, UI, and game state

const LEVELS = [
  { grid: [4, 4], speed: 1200 },
  { grid: [5, 5], speed: 900 },
  { grid: [6, 6], speed: 700 },
  { grid: [7, 7], speed: 500 }
];

let currentLevel = 0;
let score = 0;
let intervalId = null;
let gameState = 'start'; // start, playing, gameover, win
let pipeGrid = [];
const PIPE_TYPES = [
  { symbol: '┃', connects: ['up', 'down'] },
  { symbol: '━', connects: ['left', 'right'] },
  { symbol: '┏', connects: ['down', 'right'] },
  { symbol: '┓', connects: ['down', 'left'] },
  { symbol: '┗', connects: ['up', 'right'] },
  { symbol: '┛', connects: ['up', 'left'] }
];
const COLLECTIBLE = '💧';
const OBSTACLE = '☠️';

export function showStartScreen() {
  const container = document.getElementById('game-container');
  container.innerHTML = `
    <h1>AquaFlow</h1>
    <p>Guide the water through the pipes!<br>Don’t let it leak!</p>
    <button class="button" id="start-btn">Start Game</button>
    <p style="font-size:0.9em;">Inspired by charity: water</p>
  `;
  document.getElementById('start-btn').onclick = () => startGame(0);
}

export function startGame(levelIdx) {
  currentLevel = levelIdx;
  score = 0;
  gameState = 'playing';
  renderLevel();
  startWaterFlow();
}

function renderLevel() {
  const { grid } = LEVELS[currentLevel];
  const container = document.getElementById('game-container');
  container.innerHTML = `
    <div id="level">Level ${currentLevel + 1}</div>
    <div id="score">Score: <span id="score-val">0</span></div>
    <div id="pipe-grid"></div>
    <div id="progress-bar"><div id="progress"></div></div>
    <div id="message"></div>
    <button class="button" id="pause-btn">Pause</button>
  `;
  renderPipeGrid(grid[0], grid[1]);
  document.getElementById('pause-btn').onclick = pauseGame;
}

function rotateConnects(connects, rotation) {
  const dirOrder = ['up', 'right', 'down', 'left'];
  return connects.map(dir => {
    let idx = dirOrder.indexOf(dir);
    return dirOrder[(idx + rotation / 90) % 4];
  });
}

function renderPipeGrid(rows, cols) {
  pipeGrid = [];
  const grid = document.getElementById('pipe-grid');
  grid.style.gridTemplateRows = `repeat(${rows}, 48px)`;
  grid.style.gridTemplateColumns = `repeat(${cols}, 48px)`;
  grid.innerHTML = '';
  // Use the layout generated by createRandomLevelLayout
  const layout = LEVEL_LAYOUTS[currentLevel];
  for (let r = 0; r < rows; r++) {
    pipeGrid[r] = [];
    for (let c = 0; c < cols; c++) {
      let cellType = 'pipe';
      let typeIdx = 0;
      let rotation = 0;
      let symbol = PIPE_TYPES[typeIdx].symbol;
      if (layout && layout[r] && layout[r][c] !== undefined && layout[r][c] !== null) {
        if (layout[r][c] === 'start') {
          symbol = '🚰';
          cellType = 'start';
          typeIdx = 1;
          rotation = 0;
        } else if (layout[r][c] === 'end') {
          symbol = '🏁';
          cellType = 'end';
          typeIdx = 1;
          rotation = 0;
        } else if (layout[r][c] === 'obstacle') {
          symbol = OBSTACLE;
          cellType = 'obstacle';
          typeIdx = null;
          rotation = 0;
        } else if (Array.isArray(layout[r][c])) {
          typeIdx = layout[r][c][0];
          rotation = layout[r][c][1];
          symbol = PIPE_TYPES[typeIdx].symbol;
        }
      } else {
        // Fill with a random normal pipe (not a cap)
        typeIdx = Math.floor(Math.random() * PIPE_TYPES.length);
        symbol = PIPE_TYPES[typeIdx].symbol;
        cellType = 'pipe';
        rotation = Math.floor(Math.random() * 4) * 90;
      }
      const cell = document.createElement('div');
      cell.className = 'pipe-cell';
      cell.dataset.row = r;
      cell.dataset.col = c;
      cell.textContent = symbol;
      cell.style.transform = `rotate(${rotation}deg)`;
      cell.onclick = () => rotatePipe(cell);
      grid.appendChild(cell);
      pipeGrid[r][c] = { typeIdx, symbol, cellType, rotation };
    }
  }
  // Set start and end
  grid.children[0].textContent = '🚰';
  pipeGrid[0][0] = { typeIdx: 1, symbol: '🚰', cellType: 'start', rotation: 0 };
  grid.children[grid.children.length - 1].textContent = '🏁';
  pipeGrid[rows-1][cols-1] = { typeIdx: 1, symbol: '🏁', cellType: 'end', rotation: 0 };
}

function rotatePipe(cell) {
  const r = +cell.dataset.row, c = +cell.dataset.col;
  if (pipeGrid[r][c].cellType !== 'pipe') return;
  pipeGrid[r][c].rotation = (pipeGrid[r][c].rotation + 90) % 360;
  cell.style.transform = `rotate(${pipeGrid[r][c].rotation}deg)`;
  // Optionally, re-check the path after rotation:
  highlightWaterPath();
}

function startWaterFlow() {
  const { speed } = LEVELS[currentLevel];
  let progress = 0;
  let collected = 0;
  intervalId = setInterval(() => {
    progress += 100 / 20;
    document.getElementById('progress').style.width = progress + '%';
    // Check if water can flow from start to end
    const result = canWaterFlow();
    if (!result.success) {
      clearInterval(intervalId);
      gameOver();
      return;
    }
    // Update score for collectibles
    if (result.collected > collected) {
      score += (result.collected - collected) * 10;
      document.getElementById('score-val').textContent = score;
      collected = result.collected;
    }
    if (progress >= 100) {
      clearInterval(intervalId);
      nextLevelOrWin();
    }
  }, speed);
}

function canWaterFlow() {
  // BFS from start to end, track collectibles and obstacles
  const rows = pipeGrid.length, cols = pipeGrid[0].length;
  let queue = [{ r: 0, c: 0, from: null }];
  let visited = Array.from({ length: rows }, () => Array(cols).fill(false));
  let collected = 0;
  while (queue.length) {
    const { r, c, from } = queue.shift();
    if (visited[r][c]) continue;
    visited[r][c] = true;
    const cell = pipeGrid[r][c];
    if (cell.cellType === 'obstacle') return { success: false };
    if (cell.cellType === 'collectible') collected++;
    if (cell.cellType === 'end') return { success: true, collected };
    // Get possible directions from this pipe
    let connects = [];
    if (cell.cellType === 'pipe' || cell.cellType === 'start') {
      connects = rotateConnects(PIPE_TYPES[cell.typeIdx].connects, cell.rotation);
    }
    // For each direction, add neighbor if not visited
    for (const dir of connects) {
      let nr = r, nc = c, back = null;
      if (dir === 'up') { nr--; back = 'down'; }
      if (dir === 'down') { nr++; back = 'up'; }
      if (dir === 'left') { nc--; back = 'right'; }
      if (dir === 'right') { nc++; back = 'left'; }
      if (nr >= 0 && nr < rows && nc >= 0 && nc < cols && !visited[nr][nc]) {
        // Check if neighbor connects back
        const neighbor = pipeGrid[nr][nc];
        let neighborConnects = [];
        if (neighbor.cellType === 'pipe' || neighbor.cellType === 'end') {
          neighborConnects = rotateConnects(PIPE_TYPES[neighbor.typeIdx].connects, neighbor.rotation);
        }
        if (neighborConnects.includes(back) || neighbor.cellType === 'end') {
          queue.push({ r: nr, c: nc, from: dir });
        }
      }
    }
  }
  return { success: false };
}

function pauseGame() {
  if (intervalId) clearInterval(intervalId);
  document.getElementById('message').textContent = 'Paused. Click Start to resume.';
  document.getElementById('pause-btn').onclick = () => startGame(currentLevel);
}

function nextLevelOrWin() {
  if (currentLevel < LEVELS.length - 1) {
    showLevelComplete();
  } else {
    showWinScreen();
  }
}

function showLevelComplete() {
  gameState = 'levelcomplete';
  const container = document.getElementById('game-container');
  container.innerHTML = `
    <div id="message">Level Complete!</div>
    <button class="button" id="next-level-btn">Next Level</button>
  `;
  document.getElementById('next-level-btn').onclick = () => startGame(currentLevel + 1);
}

function showWinScreen() {
  gameState = 'win';
  const container = document.getElementById('game-container');
  container.innerHTML = `
    <h2>You Win!</h2>
    <div>Your Score: ${score}</div>
    <div>Did you know? 1 in 10 people lack access to clean water.</div>
    <button class="button" id="restart-btn">Restart</button>
  `;
  document.getElementById('restart-btn').onclick = () => showStartScreen();
}

function gameOver() {
  gameState = 'gameover';
  if (intervalId) clearInterval(intervalId);
  const container = document.getElementById('game-container');
  container.innerHTML += `
    <div id="message">Game Over! Water was lost.</div>
    <button class="button" id="retry-btn">Retry Level</button>
  `;
  document.getElementById('retry-btn').onclick = () => startGame(currentLevel);
}

function highlightWaterPath() {
  // Remove previous highlights
  document.querySelectorAll('.pipe-cell').forEach(cell => {
    cell.classList.remove('path-correct');
  });

  const rows = pipeGrid.length, cols = pipeGrid[0].length;
  let queue = [{ r: 0, c: 0, from: null }];
  let visited = Array.from({ length: rows }, () => Array(cols).fill(false));

  while (queue.length) {
    const { r, c, from } = queue.shift();
    if (visited[r][c]) continue;
    visited[r][c] = true;
    const cell = pipeGrid[r][c];
    // Highlight this cell
    const domCell = document.querySelector(`.pipe-cell[data-row="${r}"][data-col="${c}"]`);
    if (domCell) domCell.classList.add('path-correct');
    if (cell.cellType === 'obstacle') return;
    if (cell.cellType === 'end') return;
    // Get possible directions from this pipe
    let connects = [];
    if (cell.cellType === 'pipe' || cell.cellType === 'start') {
      connects = rotateConnects(PIPE_TYPES[cell.typeIdx].connects, cell.rotation);
    }
    // For each direction, add neighbor if not visited
    for (const dir of connects) {
      let nr = r, nc = c, back = null;
      if (dir === 'up') { nr--; back = 'down'; }
      if (dir === 'down') { nr++; back = 'up'; }
      if (dir === 'left') { nc--; back = 'right'; }
      if (dir === 'right') { nc++; back = 'left'; }
      if (nr >= 0 && nr < rows && nc >= 0 && nc < cols && !visited[nr][nc]) {
        // Check if neighbor connects back
        const neighbor = pipeGrid[nr][nc];
        let neighborConnects = [];
        if (neighbor.cellType === 'pipe' || neighbor.cellType === 'end') {
          neighborConnects = rotateConnects(PIPE_TYPES[neighbor.typeIdx].connects, neighbor.rotation);
        }
        if (neighborConnects.includes(back) || neighbor.cellType === 'end') {
          queue.push({ r: nr, c: nc, from: dir });
        }
      }
    }
  }
}

function updateNextLevelButton() {
  const nextBtn = document.getElementById('next-level-btn');
  const msg = document.getElementById('message');
  document.querySelectorAll('.path-correct, .path-incorrect').forEach(cell => {
    cell.classList.remove('path-correct', 'path-incorrect');
  });
  const rows = pipeGrid.length, cols = pipeGrid[0].length;
  let queue = [{ r: 0, c: 0, from: null, path: [] }];
  let visited = Array.from({ length: rows }, () => Array(cols).fill(false));
  let found = false;
  let lastPath = [];
  while (queue.length) {
    const { r, c, from, path } = queue.shift();
    if (visited[r][c]) continue;
    visited[r][c] = true;
    const cell = pipeGrid[r][c];
    const newPath = [...path, { r, c }];
    if (cell.cellType === 'obstacle' || cell.cellType === 'empty') continue;
    if (cell.cellType === 'end') {
      found = true;
      lastPath = newPath;
      break;
    }
    let connects = [];
    if (cell.cellType === 'pipe' || cell.cellType === 'start') {
      connects = rotateConnects(PIPE_TYPES[cell.typeIdx].connects, cell.rotation);
    }
    for (const dir of connects) {
      let nr = r, nc = c, back = null;
      if (dir === 'up') { nr--; back = 'down'; }
      if (dir === 'down') { nr++; back = 'up'; }
      if (dir === 'left') { nc--; back = 'right'; }
      if (dir === 'right') { nc++; back = 'left'; }
      if (nr >= 0 && nr < rows && nc >= 0 && nc < cols && !visited[nr][nc]) {
        const neighbor = pipeGrid[nr][nc];
        let neighborConnects = [];
        if (neighbor.cellType === 'pipe' || neighbor.cellType === 'end') {
          neighborConnects = rotateConnects(PIPE_TYPES[neighbor.typeIdx].connects, neighbor.rotation);
        }
        if (neighborConnects.includes(back) || neighbor.cellType === 'end') {
          queue.push({ r: nr, c: nc, from: dir, path: newPath });
        }
      }
    }
  }
  if (found) {
    if (nextBtn) nextBtn.disabled = false;
    if (msg) msg.textContent = 'Correct! You can go to the next level.';
    lastPath.forEach(({ r, c }) => {
      const domCell = document.querySelector(`.pipe-cell[data-row='${r}'][data-col='${c}']`);
      if (domCell) domCell.classList.add('path-correct');
    });
  } else {
    if (nextBtn) nextBtn.disabled = true;
    if (msg) msg.textContent = 'Arrange the pipes to complete the path.';
  }
}

// Patch rotatePipe and renderLevel to call updateNextLevelButton
const _rotatePipe = rotatePipe;
rotatePipe = function(cell) {
  _rotatePipe.apply(this, arguments);
  updateNextLevelButton();
};
const _renderLevel = renderLevel;
renderLevel = function() {
  _renderLevel.apply(this, arguments);
  updateNextLevelButton();
};
